### PR TITLE
IntersectsPlane()

### PR DESCRIPTION
**Pull request by vedhant**
implements #46 
This PR depends on #49

### CODE REVIEW

**Comment by vedhant** [comment]
The manual example i added here is a simple example of dragging a box in a fixed plane.

**Comment by vedhant** [comment]
@stalgiag  I have rebase and pushed. You can merge it when you are done reviewing it.

**Comment by stalgiag** [comment]
I am unable to get this working but I am also unable to get the manual test for intersects box to work anymore. `intersectsBox()` never returns true in either. If this is only on my phone then I am happy to investigate more. Interact is as expected on your end currently?

**Comment by vedhant** [comment]
I have fixed it. The problem was in the `intersectsBox()` arguments. I had forgot to change it in the examples when I had modified the parameters for it.

**Comment by vedhant** [comment]
Fixes #53 .

**Pull request merged**
