### PR TITLE
Working p5xrInput implementation

### PR DESCRIPTION
**Pull request by msub2**
I've managed to hide away all the implementation so that the only code that *should* be necessary in `draw()` to show a cube hand is 
```js
const right = getXRInput(RIGHT);
if (right != null) {
    push();
    fill(255, 255, 255);
    applyMatrix(right.pose);
    box(.15);
    pop();
}
```

It looks like I'm getting live pose data from it, but for whatever reason the box is just not drawing anywhere in the scene that I can see.

### CODE REVIEW

**Comment by msub2** [comment]
Okay, figured out what I was doing wrong; I was trying to pass it an array of values, but `applyMatrix()` only takes individual parameters, so you still have to spread the matrix contents to get it to work:
```js
const right = getXRInput(RIGHT);
if (right != null) {
    push();
    fill(255, 255, 255);
    applyMatrix(...right.pose);
    box(.15);
    pop();
}
```
Would it be worth trying to propose an upstream change?

**Comment by stalgiag** [comment]
Awesome! I've actually wanted to make that change upstream for a while. It will be easy enough to argue for.

**Comment by msub2** [comment]
Alright, I think it's in a pretty good state for now. You can retrieve the pose matrix as well as just the position in a Vector3, and I added getters to access the Gamepad buttons and axes on the controllers. So for instance, to access the value of the trigger I would just do something like this:
```js
const right = getXRInput(RIGHT);
if (right != null) {
  console.log(right.trigger.value);
}
```
and to access the thumbstick values I can just do
```js
console.log(right.thumbstick2D.x);
console.log(right.thumbstick2D.y);
```

Let me know what you think!

**Comment by stalgiag** [comment]
Looks really good! In the future, we might want to add something even more simple for input similar to [`keyTyped`](https://p5js.org/reference/#/p5/keyTyped) and [`mousePressed`](https://p5js.org/reference/#/p5/mousePressed) in p5. The ultimate goal would be to make it so that a new coder could do some simple input without knowing about property accessors or conditionals or null. This is primarily for educational contexts. For ex:
```js
function triggerDown(){
    background(100, 100, 200);
}
```
But in the meantime, this is great for anyone that is slightly more experienced which likely accounts for anyone using the library currently.

@all-contributors please add @msub2 for design. (I know design isn't quite right but there isn't anything specifically for API design)

**Comment by stalgiag** [comment]
@all-contributors please add @msub2 for design.

**Pull request merged**
