### PR TITLE
Use Headless Chrome for unit testing

### PR DESCRIPTION
**Pull request by vedhant**

### CODE REVIEW

**Comment by vedhant** [comment]
I have refactored the unit test of ```createVRCanvas()``` to make it more like a unit test.

**Comment by stalgiag** [comment]
I added a comment in #36.

I also just wanted to point out that you should be linting these files using the configuration in the project folder. I use Visual Studio Code as my IDE and I am able to automatically lint with CTRL+SHIFT+P ESLint: Fix all autofixable problems. If you use another IDE we can figure that out separately.

Also (and this is partially my fault by putting a bad example in the "docs" script command), but the `node_modules/.bin` folder is automatically added to the PATH by npm when you run a script so you don't need to direct to the module file directory in the script in package.json. Simply writing `karma start karma.conf.js` will do well.

**Comment by vedhant** [comment]
`karma start karma.conf.js` is not working for me. That's why I used `./node_modules/karma/bin/karma`. I think karma-cli needs to be installed for just `karma` to work.

**Comment by vedhant** [comment]
As I pointed out in #36 , I am going ahead with bdd style for mocha.

**Comment by vedhant** [comment]
I have fixed the errors mentioned in #36 and after a little clean up, I squashed commits and forced pushed.
Only thing remaining is to decide whether the current way of deleting `navigator.xr` suffices or whether to delete polyfill stuff in a better way.

**Comment by vedhant** [comment]
Fixes #36

**Comment by stalgiag** [comment]
Looks like a great start! I would say merge this whenever you would like, once everything feels sufficiently clean. Additions can be merged in future PRs. I think this one can simply serve as a foundation.

**Pull request merged**
