### PR TITLE
Feat/hand tracking

### PR DESCRIPTION
**Pull request by TiborUdvari**
Not quite ready to merge this, but to follow up on the API proposal in #216 it would look something like this

https://github.com/stalgiag/p5.xr/assets/1434442/3c4356b1-56d6-44aa-a587-525e81f50d63

```js
function preload() {
  createARCanvas();
}

function setup() {
  describe("A sphere on your right index finger");
  mainHandMode(RIGHT);
}

function draw() {
  normalMaterial();
  push();
  translate(finger.x, finger.y, finger.z);
  sphere(0.01);
  pop();
}
```

### CODE REVIEW

**Comment by TiborUdvari** [comment]
https://github.com/stalgiag/p5.xr/assets/1434442/dcff6863-a1a4-4148-a599-69712fa628b0

This would allow to have quick interactions like this in an "active area", a spatial equivalent to 

```js
function draw() {
  ellipse(mouseX, mouseY, 10, 10);
}
```

**Comment by TiborUdvari** [comment]
Full hands

https://github.com/stalgiag/p5.xr/assets/1434442/3992a974-c488-4fc6-859c-e7e503d9a09d

```js
function preload() {
  createARCanvas();
}

function setup() {
  describe("Spheres on all the skeletal joints of the hand.");
}

function draw() {
  normalMaterial();
  for (let i = 0; i < hands.length; i++) {
    const joint = hands[i];
    push();
    translate(joint.x, joint.y, joint.z);
    sphere(0.01);
    pop();
  }
}
```

**Comment by TiborUdvari** [comment]
Other experiments here: https://www.tiborudvari.com/sketchbook

**Comment by TiborUdvari** [comment]
Also worth mentioning this depends on the #215 refactor

**Comment by stalgiag** [comment]
Amazing! It could be fun to think through and iterate on what a beginner-friendly API would be for this. That said, I think `finger` as the last joint on the index of the hand set with `mainHandMode` is a great start.

**Comment by TiborUdvari** [comment]
Close because did it in #242

**Pull request closed without merging**
